apiVersion: v1
kind: ServiceAccount
metadata:
  name: support-runbook-copilot
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::126366239504:role/AgentApiIRSA-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-runbook-copilot
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-runbook-copilot
  template:
    metadata:
      labels:
        app: support-runbook-copilot
    spec:
      serviceAccountName: support-runbook-copilot
      containers:
        - name: support-runbook-copilot
          image: 126366239504.dkr.ecr.eu-central-1.amazonaws.com/support-runbook-copilot:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: CLAUDE_MODEL_ID
              value: eu.anthropic.claude-sonnet-4-5-20250929-v1:0
            - name: AWS_REGION
              value: eu-central-1
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
